### ISSUE TITLE
latest version xevd lib function xevd_pull cause build error

### ISSUE THREAD

**Issue by MichaelShu3333** [mpeg5/ffevc#15]
When I build latest version of ffevc with --enable-libxevd, build error, and I found  in ffevc-main/ffmpeg-subtree/libavcodec/libxevd.c

xevd lib(v0.3.1)  function xevd_pull paramters  from 3 to 2, so not need third parameter， so do not need third parameter:
ret = xevd_pull(ctx->id, &(imgb), &(ctx->opl));	-->	ret = xevd_pull(ctx->id, &imgb);

**Comment by dariusz-f** [comment]
We're working on that, soon fix will be provided.

**Comment by dariusz-f** [comment]
Fixed in #16
